postgres.host: postgresql.service.consul
postgres.port: 5432
postgres.maintenance_db: run_tracking
postgres.user: butler_admin
postgres.password: butler
postgres.pass: butler
postgres.max_connections: 1550
postgres.listen_addresses: "*"
postgres.shared_buffers: 4GB
